name: susya
description: App for Plant disease predictor impulse hackathon
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  get: ^4.6.6
  google_sign_in: ^6.2.1
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  geolocator: ^13.0.1
  share_plus: ^10.1.1
  dio: ^5.7.0
  flutter_plugin_android_lifecycle: ^2.0.23
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/